### ISSUE TITLE
Resolve R-CMD-Check Warnings

### ISSUE THREAD

**Issue by warner-pra** [jordagaman/zddr#24]
Causing CMD-check to fail:

<img width="654" alt="image" src="https://user-images.githubusercontent.com/78666697/123010702-1fa9c000-d38d-11eb-98e4-04dca0f31a97.png">

**Comment by warner-pra** [comment]
@jordagaman: Not sure what's going on with the first warning, do the arguments need to match here between the generic and method? For the second, is the `Q` argument being used in the function?

**Comment by jordagaman** [comment]
Add a PR to close this out - thanks for diving in!
